### ISSUE TITLE
Får inte fram card

### ISSUE THREAD

**Issue by backisen** [isabellaalstrom/pollenkoll-card#1]
Jag får inte fram card trots korrekta inställningar i ui-lovelace.yaml.

Detta finns i loggen:
`/local/pollenkoll-card.js:73:35 Uncaught TypeError: Cannot read property 'attributes' of undefined`

**Comment by krissen** [comment]
Hade samma problem. Tror att felet jag gjorde då var att ha staden med stor första bokstav. (Måste vara bara små bokstäver.) Sen kraschar kortet också / syns inte, om man försöker lägga till sensor som f. n. inte stöds (ex. vis sälg).

**Comment by TobbeWendt** [comment]
Jag får inte kortet att fungera med städer som har svenska tecken (har testast med Hässleholm och Göteborg), det blir blankt och hela den sida som man lägger in kortet på blir blank (troligen samma som tidigare inlägg). 
Fungerar perfekt med Stockholm men det glädjer inte en skåning.
I övrigt ett jättebra initiativ och fint kort.

**Comment by fnordpojk** [comment]
Samma problem här, dock noterar jag att Göteborg faktiskt inte har nån data för day3, kanske det som är problemet i mitt fall?

**Comment by sundberg84** [comment]
Får inte fram för Kristianstad, verken med liten eller stor bokstav.

**Comment by kernehed** [comment]
Jag får inte fram med Gävle heller.

**Comment by krissen** [comment]
Säkert dum fråga, men vissst fungerar sensorerna, @sundberg84 och @kernehed? Ni har t. ex. `sensor.pollenniva_kristianstad_alm_day_0` resp. `sensor.pollenniva_gavle_alm_day_0` och så vidare? (Eller vilka allergener ni valt.)

**Comment by kernehed** [comment]
@krissen 

Yes, det fungerar..
Dock måste jag använda stor bokstav i konfigurationen för pollenniva.
Kör jag med liten bokstav fungerar inte sensorerna.

```
platform: pollenniva
sensors:
  - city: Gävle
    days_to_track: 3
    allergens:
      - Al
      - Alm
      - Ambrosia
      - Asp
      - Sälg
      - Björk
      - Bok
      - Ek
      - Gråbo
      - Gräs
      - Hassel
```
